### ISSUE TITLE
9 Patch Erro(Gradle Build throws this)

### ISSUE THREAD

**Issue by nilcool** [luongthanhlam/4pics1word#2]
AAPT err(Facade for 1323334660): ERROR: 9-patch image E:\Projects\4pics1word-master2\app\src\main\res\drawable-hdpi\btn_key.9.png malformed.
AAPT err(Facade for 1323334660):        Frame pixels must be either solid or transparent (not intermediate alphas).
AAPT err(Facade for 1323334660):        Found at pixel #11 along top edge.
AAPT err(Facade for 1323334660): ERROR: 9-patch image E:\Projects\4pics1word-master2\app\src\main\res\drawable-hdpi\btn_green_pressed.9.png malformed.
AAPT err(Facade for 1323334660):        Frame pixels must be either solid or transparent (not intermediate alphas).
AAPT err(Facade for 1323334660):        Found at pixel #48 along top edge.
AAPT err(Facade for 1323334660): ERROR: 9-patch image E:\Projects\4pics1word-master2\app\src\main\res\drawable-hdpi\com_facebook_button_grey_pressed.9.png malformed.
AAPT err(Facade for 1323334660):        No marked region found along edge.
AAPT err(Facade for 1323334660):        Found along top edge.
AAPT err(Facade for 1858634334): ERROR: 9-patch image E:\Projects\4pics1word-master2\app\src\main\res\drawable-hdpi\btn_grey.9.png malformed.
AAPT err(Facade for 1858634334):        Frame pixels must be either solid or transparent (not intermediate alphas).
AAPT err(Facade for 1858634334):        Found at pixel #37 along top edge.
AAPT err(Facade for 1858634334): ERROR: 9-patch image E:\Projects\4pics1word-master2\app\src\main\res\drawable-hdpi\bg_shop.9.png malformed.
AAPT err(Facade for 1858634334):        Must have one-pixel frame that is either transparent or white.
AAPT err(Facade for 2131851724): ERROR: 9-patch image E:\Projects\4pics1word-master2\app\src\main\res\drawable-hdpi\com_facebook_button_grey_normal.9.png malformed.
AAPT err(Facade for 2131851724):        Frame pixels must be either solid or transparent (not intermediate alphas).
AAPT err(Facade for 2131851724):        Found at pixel #2 along top edge.
AAPT err(Facade for 2131851724): ERROR: 9-patch image E:\Projects\4pics1word-master2\app\src\main\res\drawable-hdpi\bg_jokerdialog.9.png malformed.
AAPT err(Facade for 2131851724):        Must have one-pixel frame that is either transparent or white.
AAPT err(Facade for 2131851724): ERROR: 9-patch image E:\Projects\4pics1word-master2\app\src\main\res\drawable-hdpi\bg_coins.9.png malformed.
AAPT err(Facade for 2131851724):        Frame pixels must be either solid or transparent (not intermediate alphas).
AAPT err(Facade for 2131851724):        Found at pixel #10 along top edge.
AAPT err(Facade for 2131851724): ERROR: 9-patch image E:\Projects\4pics1word-master2\app\src\main\res\drawable-hdpi\btn_green.9.png malformed.
AAPT err(Facade for 2131851724):        No marked region found along edge.
AAPT err(Facade for 2131851724):        Found along top edge.
AAPT err(Facade for 2131851724): libpng error: Not a PNG file
AAPT err(Facade for 2131851724): ERROR: 9-patch image E:\Projects\4pics1word-master2\app\src\main\res\drawable-hdpi\com_facebook_button_grey_focused.9.png malformed.
AAPT err(Facade for 2131851724):        Frame pixels must be either solid or transparent (not intermediate alphas).
AAPT err(Facade for 2131851724):        Found at pixel #2 along top edge.
Error:Execution failed for task ':app:mergeDebugResources'.

> Some file crunching failed, see logs for details
> Information:BUILD FAILED
> Information:Total time: 1 mins 19.62 secs
> Information:1 error
> Information:0 warnings
> Information:See complete output in console

**Comment by t1ld3x** [comment]
fixed, please pull latest changes from master!
